url: https://wemakeappsllc.com
baseurl: ""

# Site settings
title: We Make Apps
email: hello@wemakeappsllc.com
description: "At We Make Apps, we make apps."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80DAEB
  secondary: 6fd5e8
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jason
  pic: 1
  position: iOS / Apple Watch / UI/UX / Design
  social:
    - title: twitter
      url: jasontezanos
    - title: linkedin
      url: https://www.linkedin.com/pub/jason-tezanos/35/702/212

- name: Damien
  pic: 2
  position: Ruby on Rails / RubyMotion / Databases / Angular
  social:
    - title: twitter
      url: dam13n
    - title: linkedin
      url: https://www.linkedin.com/in/damiensutevski

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/wemakeappsllc
  - title: facebook
    url: https://www.facebook.com/pages/We-Make-Apps/107448066258928


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty